baseurl = "https://rdf4j.org/" 
DefaultContentLanguage = "en"
title = "Eclipse rdf4j"
theme = "hugo-solstice-theme"
metaDataFormat = "yaml"
googleAnalytics = ""
themesDir = "themes/"
disableKinds = ["taxonomy", "taxonomyTerm"]

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[Params]
  google_tag_manager = ""
  description = "Eclipse rdf4j: Scalable RDF for Java developers."
  subtitle = "Eclipse Foundation"
  seo_title_suffix = " | The Eclipse Foundation"
  keywords = ["hugo", "solstice", "eclipse foundatiou"]
  logo = "images/rdf4j-logo-orange-114.png"
#  favicon = "images/favicon.ico"
#  styles = "css/styles.css"
#  js = "js/solstice.js"
  gcse = ""
# header_wrapper_class = "header-default-bg-img"
#  call_for_action_text = "Download"
#  call_for_action_url = "https://www.eclipse.org/downloads"
#  call_for_action_icon = "fa-download"
  
[Author]
  name = "Christopher Guindon"
  website = "https://www.eclipse.org"
  email = "webdev@eclipse-foundation.org"
  facebook = "eclipse.org"
  twitter = "EclipseFdn"
  youtube = "EclipseFdn"
  googleplus = "+Eclipse"
  linkedin = "company/eclipse-foundation/"

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

[[menu.main]]
    name = "News"
    url = "/news/"
    weight = 2

[[menu.main]]
    name = "Documentation"
    identifier = "documentation"
    url = "/documentation/"
    weight = -3
